### ISSUE TITLE
Wifi not working (AX1650 - AX201)

### ISSUE THREAD

**Issue by BenDevelopment** [zachs78/MacOS-XPS-9500-OpenCore#1]
Hi @zachs78, thank you for your job !

I'm able to boot the installer but I cannot run the installation process because it says that I have to be connected to internet.
I've tried the kext you've recommended (itlwmx) but it doesn't works. I've tried this one too: https://github.com/OpenIntelWireless/itlwm but I still cannot see my wifi working.
My question is, what is you wifi card (I don't know if there are some XPS 9500 with different wifi card version)? Mine is AX1650 (considered as AX201). As you can see here in my comment, it should works: https://github.com/OpenIntelWireless/itlwm/issues/36#issuecomment-682047960.

**Comment by robotblox** [comment]
Hey @BenDevelopment, I can help you out here. itlwm isn't working in the installer because it requires the Heliport application to function properly. You can only install Heliport once you've got a working MacOS install. If you're making your installer from a Windows machine, you'll only be able to use the recovery installer and you'll need internet for that as it installs the OS from Apple's servers. Here are a few things that you can try:

1) Create the installer with a Mac or with a Windows machine running a Virtual Machine of Mac using the following guide: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html

(as far as I know installers made with Windows can only create recovery media installers, whereas installers made with MacOS have the full OS image included and therefore do not require internet connections)

2) This one is a little more experimental, and I'm not sure if it'll work. You're going to need an Android phone or tablet for this.

Go to my repo: https://github.com/robotblox/XPS-15-9500-Catalina-10.15.6 and use "HoRNDIS.kext" from my kext folder. I extracted the kext file from the official release a little while back to make it easier to use. What HoRNDIS basically does is use your Android device as an internet tether. Boot into the MacOS installer and plug in your device to your laptop. After that, you should get internet connectivity. The Dortania guide mentions it but I didn't have my USB ports working when I was in the installer, (which was fixed by zachs78, so it should be fine) so I didn't get a chance to test it out.

Let me know if you figure it out!

**Comment by BenDevelopment** [comment]
Thank you @robotblox, I can now pass this step.
I've tried the second solution first, using my Android device but it did not worked. The first solution worked (using my Mac VM).
Now, I've another problem with the next step, I'll make a new issue. (https://github.com/zachs78/MacOS-XPS-9500-OpenCore/issues/2)
