### ISSUE TITLE
Drives not shown on installer

### ISSUE THREAD

**Issue by BenDevelopment** [zachs78/MacOS-XPS-9500-OpenCore#2]
Hi,

I'm stuck on the installing processus at the step where you have to select the installation drive. In my case, there is not drive listed. When I open the diskUtility, the only disk I can see (even with the "show all volumes" option enabled) is the usb stick I'm using to boot my MacOS installer.
I've tried to add this kext https://github.com/dortania/OpenCore-Install-Guide/blob/master/extra-files/CtlnaAHCIPort.kext.zip as described here: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html#sata-drives-not-shown-in-diskutility but nothing changes.
Curently, SATA Operation is set to RAID On (Intel Rapid Restore Technology). If I change it for AHCI, the MacOS installer fail to boot (it restarts after the loading screen).

I've two nvme in my XPS 9500, first is **Micron 2200s nvme 1042gb** which is not supported, second is **SAMSUNG V-Nand 970 EVO** (**not** EVO Plus version).  As far as I know this Samsung NVME is not unsupported (according to this unsupported list https://dortania.github.io/OpenCore-Install-Guide/macos-limits.html#storage-support).

Any idea on how I can make my drive visible for the installer?

Thank you!

**Comment by zachs78** [comment]
You need to set it to AHCI. Might've been a kernel panic. Try https://github.com/acidanthera/NVMeFix

I think with the Evo 970 you'll need a firmware update too. Disable the Micron in the BIOS is you're sure it's not supported to rule that out.

I got a Mac compatible NVMe SSD for this purpose so I didn't encounter any problems with the drives.

**Comment by BenDevelopment** [comment]
I still cannot boot the installer when I'm in AHCI mode even with the NVMeFix Kext.
I've checked my Evo 970 firmware with Magician Software, it says that it's already up to date.
I've disabled the Micron NVMe but the installer still crashes.
I'll keep looking in Google for a solution. If you have any suggestion feel free :) !

**Comment by BenDevelopment** [comment]
Thank you it works well now!

EDIT: 
I can run my MacOS installation only when my Micron is disabled. If I enable it in BIOS, my MacOS installation crashes at loading screen. Does someone knows a workaround for this?

**Comment by robotblox** [comment]
@BenDevelopment Hi Ben,

What you'd need to do is create an SSDT that tells Mac OS X to only disable your Micron drive when you boot. This SSDT will need to be custom made to fit your drive specifically, and I'm not too familiar with editing ACPI tables so I'm afraid I won't be much of a help.

I can get you started though. The keywords you're looking for are something along the lines of "SSDT to disable one m.2 slot"

There are a few people who have posted on the tonymacx86 and insanelymac forums with similar issues and have gotten help, so that might be a good place to start. I'll link a few threads from the same person below. Good luck!

https://www.tonymacx86.com/threads/how-to-disable-specific-nvme-m-2-slot-via-dsdt-hide-unsupported-970-evo-plus.275416/

https://www.insanelymac.com/forum/topic/338320-how-to-disable-specific-nvme-m2-slot-via-dsdt-hide-unsupported-970-evo-plus/
